name: Desafio

on:
  workflow_dispatch:

env:
  APP_NAME: MeuApp

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: v1

    steps:
      - name: Passo 1
        env:
          STEP_TEMP: Processando
        run: |
          echo "APP: $APP_NAME"
          echo "VERSION: $BUILD_VERSION"
          echo "TEMP: $STEP_TEMP"

      - name: Passo 2
        run: echo "TEMP fora: $STEP_TEMP"

      - name: Passo 3
        run: echo "$GITHUB_ACTOR $GITHUB_REPOSITORY $RUNNER_OS"

      - name: Passo 4
        run: echo "BUILD_HASH=$RANDOM" >> $GITHUB_ENV

      - name: Passo 5
        run: echo "HASH $BUILD_HASH"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Passo 6
        run: |
          echo "${{ vars.URL_AMBIENTE }}"
          echo "${{ secrets.API_TOKEN_PROD }}"
