name: Desafio de Variaveis e Escopos

on:
  workflow_dispatch:

env:
  APP_NAME: MeuAppIncrivel

jobs:
  build_app:
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: v1.0.0

    steps:
      - name: Passo 1
        echo "APP_NAME: $APP_NAME | VERSION: $BUILD_VERSION"

      - name: Passo 2
        run: echo "STEP_TEMP: $STEP_TEMP"

      - name: Passo 3
        run: echo "Usuario $GITHUB_ACTOR | Repo $GITHUB_REPOSITORY | SO $RUNNER_OS"

      - name: Passo 4
        run: echo "BUILD_HASH=$RANDOM" >> $GITHUB_ENV

      - name: Passo 5
        run: echo "HASH: $BUILD_HASH"

  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Passo 6
        run: |
          echo "URL: ${{ vars.URL_AMBIENTE }}"
          echo "TOKEN: ${{ secrets.API_TOKEN_PROD }}"
